apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "service.name" . }}-configmap
  labels:
    app.kubernetes.io/name: {{ template "service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: {{ template "service.name" . }}