apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "service.name" . }}
  labels:
    app.kubernetes.io/name: {{ template "service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "service.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "service.name" . }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ include "service.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: "photoprism/photoprism:230506"
        ports:
        - containerPort: 2342
        env:
          - name: PHOTOPRISM_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "service.name" . }}
                key: PHOTOPRISM_ADMIN_PASSWORD
          - name: PHOTOPRISM_ADMIN_USER
            value: {{ .Values.environment.PHOTOPRISM_ADMIN_USER }}
          - name: PHOTOPRISM_STORAGE_PATH
            value: {{ .Values.environment.PHOTOPRISM_STORAGE_PATH }}
        volumeMounts:
          - name: "forever-robot"
            mountPath: {{ .Values.environment.PHOTOPRISM_STORAGE_PATH }}
      volumes:
        - name: "forever-robot"
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ template "service.name" . }}
        {{- else }}
          emptyDir: {}
        {{- end -}}  
      