apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: verbose-robot-network-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: {{ template "service.name" . }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      ports:
        - protocol: TCP
          port: 2342   
  egress:
    - to:
      ports:
        - protocol: TCP
          port: 2342