apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "service.name" . }}
spec:
  accessModes: 
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi