apiVersion: v1
kind: Secret
metadata:
  name: {{ template "service.name" . }}
  labels:
    app.kubernetes.io/name: {{ template "service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    helm.sh/resource-policy: keep
    helm.sh/hook: "pre-install"
    helm.sh/hook-delete-policy: "before-hook-creation"
type: Opaque
data:
  PHOTOPRISM_ADMIN_PASSWORD: {{ randAlphaNum 22 | b64enc | quote }}
