apiVersion: v1
kind: Service
metadata:
  name: {{ template "service.name" . }}
  type: ClusterIP
  labels:
    app.kubernetes.io/name: {{ template "service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app.kubernetes.io/name: {{ template "service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2342